### ISSUE TITLE
Problema encontrando Terminal

### ISSUE THREAD

**Issue by x-glitch-z** [LevisWings/Auto-PWE#1]
Hola, tengo un problema al instalar Auto-PWE. 
Primero antes de empezar le he dado update y upgrade a Parrot. 
Luego de dar el primer paso y completarlo se indica: [!] Logearse indicando bspwm y ejecutar el script nuevamente para el paso 2...
Al salir y entrar de nuevo a Parrot en bspwm  no encuentro la forma de abrir el Terminal. Los  comandos no estan operativos.
Por favor ayuda.

**Comment by daleplaydaleplay** [comment]
Hola WalkingCell. Por lo que leo, no puedes usar el shortcut Windows + Enter. Intenta probar a usar el rofi con Windows + D y escribir "gnome-terminal". Si el problema persiste, necesito que me especifiques algunas cosas:
1. ¿Usas Virtual Box o VMware?
2. Versión de Linux que estás usando.

Saludos.

**Comment by x-glitch-z** [comment]
Gracias por responder tan rapido. He tratado lo que me pides y tampoco me presenta Rofi. 
Aparte, tambien me sale: Failed to run redshift. Lo cual he suprimido entrando al terminal en Xsession y poniendo: sudo apt remove redshift. 
Otra cosa, esta es una maquina clonada de una maquina Parrot Security 4.10 nueva que cree, la razon que clone esta es para no tener que estar haciendo el setting de el Guest Additions nuevamente. 
Ahora, En este clon que estoy usando tuve que especificar nuevamente la parte del GRUB boot loader. Quizas aqui hay un error al especificar el harddrive? Puies puse el primero de VirtualBox.
Respondiendo a lo que me preguntas. Estoy usando Virtual Box. La maquina es el Parrot security 4.10 y la maquina host es una Mac.
Gracias.

**Comment by daleplaydaleplay** [comment]
Sin duda, es un problema con los shorcuts. Con el redshift no te preocupes que no tiene nada que ver. Estaba por recomendarte instalar la Guest-Additions pero como ya lo tienes, estoy en duda si esto pudo generar un problema. Creo que al usar una máquina clonada ya preconfigurada, puede dar conflictos (lo digo porque casi todos usaron una nueva ISO cuando se les presento este problema). Comprueba lo siguiente en estos archivos iniciando en MATE o Default XSession:
```
cat /home/<tu usuario>/.config/bspwm/bspwmrc # Busca la parte de bspc config pointer_modifier y si está en "mod1"
cat /home/<tu usuario>/.config/sxhkd/sxhkdrc # Busca el comentario "terminal emulator", tiene que estar el "Super + Return" y abajo el "gnome-terminal".
# De paso, intentá abrir una gnome-terminal con Rofi como te explique anterioremente (rofi -show run -> Escribís: gnome-terminal -> Enter)
cat /home/<tu usuario>/.xinitrc # Tiene que estar el "sxhkd &" y abajo "exec bspwm".
```
Si lo anterior se encuentra en esos archivos, y pudiste abrir el gnome-terminal, intentá por última vez iniciar sesión con bspwm y abrir una terminal (esto lo digo porque a veces tarda en cargar la configuración del sxhkd, aunque es rarísimo). Si no funciona, lo que te recomiendo (y me duele hacerlo) es hacerlo con una nueva ISO. Veo que estas en Discord, así que puedes escribirme por privado (Levi's Wings) también si así lo deseas para intentar solucionar el problema más rápido, además de que la comunidad siempre aporta algo. No obstante, voy a hacer una nueva instalación en Parrot para comprobar si obtengo el mismo problema. Saludos!

**Comment by x-glitch-z** [comment]
Este problema lo solucione modificando el prefix Super por el Alt, en el archivo sxhkdrc.
Gracias LevisWings por la ayuda.
