### ISSUE TITLE
Problema con Redshift

### ISSUE THREAD

**Issue by JarssS8** [LevisWings/Auto-PWE#2]
Estoy usando una maquina virtual y el sistema operativo parrot security de MATE.
Tengo un problema desde que inicio sesion y aunque le de a cerrar esa ventana continua apareciendo.
Nunca he usado redshift y no se como se usa o como solucionarlo, me pasa justo despues de correr el script con el parametro 1 y volver a hacer login.
![image](https://user-images.githubusercontent.com/47742360/106274886-4415cc00-6235-11eb-83cb-42d4e61c7af2.png)

**Comment by daleplaydaleplay** [comment]
Abri una terminal y desinstalalo con este comando:
```
sudo apt purge redshift redshift-gtk -y 
```
El Redshift es como un gestor de brillo según el horario de tu zona, es como el modo nocturno, así que no te preocupes al desinstalarlo. Saludos! Ya mismo lo estoy solucionando en el script para que no ocurra esto.

**Comment by JarssS8** [comment]
Vale, muchas gracias. 
Estaba buscando donde se aplicaba en el codigo y no lo encontraba, no se me habia ocurrido simplemente desinstalarlo😅😅😅.
