### ISSUE TITLE
Unicode chrome  character problem 

### ISSUE THREAD

**Issue by TheCyberpunker** [LevisWings/Auto-PWE#3]
hi actually chrome is displaying a box in replace of a special chracter or emoji, do you know how to solve?  🧐

**Comment by TheCyberpunker** [comment]
> hi actually chrome is displaying a box in replace of a special chracter or emoji, do you know how to solve?

Solution: already fixed.
sudo apt-get install ttf-ancient-fonts -y
sudo apt install fonts-noto -y
fc-cache -v ( or fc-cache -f -v)
sudo reboot

Done!

**Comment by daleplaydaleplay** [comment]
Thank you for sharing the solution with the community. I really appreciate that you solved it on your own :)
