### ISSUE TITLE
Problema para hacer capturas

### ISSUE THREAD

**Issue by shroudri** [LevisWings/Auto-PWE#4]
Usando bspwm + sxhkd + polybar + rofi

Al hacer Impr Pant, no se abre el menú que se abría en el escritorio Mate para hacer capturas de pantalla.

Lo máximo que he conseguido ha sido abriendo mate-screenshot desde rofi, pero al hacer la captura aparece rofi en medio de la pantalla con lo cual es imposible capturar nada.

Shift + Impr Pant para capturar solo una región tampoco funciona.

**Comment by daleplaydaleplay** [comment]
Hola therodri2. He estado probando la herramienta, y se puede hacer configurando unos shortcuts (atajos de teclado) que no sean la tecla ImpPnt. Para hacerlo son los siguientes pasos:
### Pasos:
- Abrir el archivo ~/.config/sxhkd/sxhkdrc con nano o vim:
```
nano ~/.config/sxhkd/sxhkdrc
```
- Abajo de todo, donde dice "CUSTOM", puedes insertar tus propios atajos, y un ejemplo sería el siguiente:
```´
# Capturar pantalla instantaneamente
super + shift + f
    mate-screenshot

# Capturar una region de la pantalla
super + shift + h
    mate-screenshot --area
```
- Breve explicación: *super* es la tecla Windows, *shift* es recomendable usarlo para estos atajos (aunque eso es decisión propia), y luego le puedes asignar una letra que no se esté ocupando (en estos ejemplos use las teclas *f* y *h* que no entran en conflicto con otros shortcuts). Recordar hacer una tabulación en esta parte:
```
super + shitf + f
<TABULAR ESTA PARTE>mate-screenshot
```
- Luego, presiona las teclas "Windows + Alt + R" para actualizar los cambios y cerras la sesión con `kill -9 -1`.

Vuelves a iniciar sesión y ya debería estar. Las teclas en este caso son:
- Windows + Shift + F : Capturar pantalla
- Windows + Shift + H : Capturar una región de la pantalla.

Si necesitas otras opciones que proporciona la herramienta *mate-screenshot*, puedes hacer `mate-screenshot --help` y crear más shortcuts agregando los parámetros disponibles (como **--area**). Espero lo hayas solucionado, saludos!

PD: Puede ser que haya una tecla con ImpPnt (para evitar hacer shotcuts más largos), pero desconozco como es el nombre en este momento.

**Comment by therodri2** [comment]
Brutal, lo que he estado probando ha funcionado bien.

Muchísimas gracias por tu ayuda y tu pronta respuesta

**Comment by shroudri** [comment]
Brutal, lo que he estado probando ha funcionado bien.

Muchísimas gracias por tu ayuda y tu pronta respuesta

Cierro esto!
