### ISSUE TITLE
powerlevel10k error

### ISSUE THREAD

**Issue by akil3s79** [LevisWings/Auto-PWE#5]
Buenas!

Ante todo, gracias por el currazo que os habéis pegado para hacer esto :)

He detectado un problema al lanzar el script 2, no se puede conectar al github de powerlevel10k (https://gitee.com/romkatv/powerlevel10k.git):
Clonando en '/home/user/powerlevel10k'...
fatal: no es posible acceder 'https://gitee.com/romkatv/powerlevel10k.git/':Failed to connect to gitee.com port 443: Conexión rehusada
Por el navegador tampoco va. ¿Hay alternativa a esto?

¡Gracias y buen finde!

Vale, edito:

He encontrado esto:
https://github.com/romkatv/powerlevel10k.git

RE-RE EDITO:

Problema, solucionado. Cambias el link en ambas funciones y funciona sin problema:

function powerlevel10k_zsh_username(){
        # Eliminar existencias
        rm -f -r ~/powerlevel10k 2>/dev/null
        rm -f ~/.zshrc 2>/dev/null
        # Instalando powerlevel10k
        echo -e "${yellow}\n$(cat $info_path/$info_lang | awk 'NR==76') $(whoami)${end}\n"
        cd && git clone --depth=1  https://github.com/romkatv/powerlevel10k ~/powerlevel10k; check
        echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc ; check
        echo -e "${purple}\n$(cat $info_path/$info_lang | awk 'NR==77') $(whoami)\n${end}"
        sleep 5
        zsh
}
function powerlevel10k_zsh_root(){
        # Eliminar existencias
        sudo rm -f -r /root/powerlevel10k 2>/dev/null
        sudo rm -f /root/.zshrc 2>/dev/null
        # Instalando powerlevel10k
        sudo echo -e "${yellow}\n$(cat $info_path/$info_lang | awk 'NR==76') root${end}\n"
        sudo git clone --depth=1 https://github.com/romkatv/powerlevel10k /root/powerlevel10k; check
        sudo echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> /root/.zshrc; check
        echo -e "${purple}\n$(cat $info_path/$info_lang | awk 'NR==77') root\n${end}"
        sleep 5
        sudo zsh
}

**Comment by daleplaydaleplay** [comment]
Buenísima @akil3s79. Tal como decís, las rutas para la instalación del powerlevel10k cambiaron tal como se muestra en la [documentación oficial](https://github.com/romkatv/powerlevel10k#installation). Al parecer la ruta antigua (https://gitee.com/romkatv/powerlevel10k.git) será más usada por los usuarios de China Continental. Muchas gracias por reportarlo, ya está actualizado.
